Marketplace
hyperbridge/governance-protocol pull request #3
Opened 2017-12-24 10:49 UTC by 0xwalid

2017-12-24 11:11 UTC, ericmuyser commented on smart-contracts/ethereum/contracts/UserProfile.sol
> +    mapping (uint => App) apps;  // app_address  => app_version_id
app_address? so should this be `mapping (address => App) apps;`

2017-12-24 11:11 UTC, ericmuyser commented on smart-contracts/ethereum/contracts/UserProfile.sol
> +  address market_place;
No underscore

2017-12-24 11:14 UTC, ericmuyser commented on smart-contracts/ethereum/contracts/MarketPlace.sol
> +    require (apps[_id].id == _id && apps[_id].versions[_version].version == _version);
I don't think we need validation on gets, just sets

2017-12-24 11:17 UTC, ericmuyser commented on smart-contracts/ethereum/contracts/MarketPlace.sol
> +    mapping  (uint => AppVersion)  versions;
We're going to need an array of versions so we know which are available (mapping can't be iterated)

2017-12-24 11:18 UTC, ericmuyser commented on smart-contracts/ethereum/contracts/MarketPlace.sol
> +  function submitAppForReview(string _name, uint _version, string _category, string _files, string _checksum, uint _required_permissions) public returns(bool res) {
I think we may need to change version to a `string` to support semver

2017-12-24 11:19 UTC, ericmuyser commented on smart-contracts/ethereum/contracts/UserProfile.sol
> +  modifier onlyOwner() {
Note for later: we probably want a `transferOwnership` method

2017-12-24 11:19 UTC, ericmuyser commented on smart-contracts/ethereum/contracts/UserProfile.sol
> +  modifier onlyOwner() {
That either the owner or a delegate can use

2017-12-24 11:20 UTC, ericmuyser commented
Note: App approval isn't in here yet

2017-12-24 12:41 UTC, contextlimit requested changes
Minor changes, semver version string, etc.

2017-12-25 14:19 UTC, 0xwalid commented on smart-contracts/ethereum/contracts/MarketPlace.sol
> +  function submitAppForReview(string _name, uint _version, string _category, string _files, string _checksum, uint _required_permissions) public returns(bool res) {
I agree.

2017-12-25 14:20 UTC, 0xwalid commented on smart-contracts/ethereum/contracts/MarketPlace.sol
> +    mapping  (uint => AppVersion)  versions;
right we need that for sure

2017-12-25 14:29 UTC, 0xwalid commented on smart-contracts/ethereum/contracts/UserProfile.sol
> +    mapping (uint => App) apps;  // app_address  => app_version_id
sorry the comment is misleading. i initially planned to give addresses for the apps but changed it to int. no need to have an independent address for the apps since they are hosted by the our contract

2018-01-10 12:51 UTC, merged